name: Proof HTML
on:
  push:
  workflow_dispatch:
jobs:
  build:Software Development
    runs-on: ubuntu-latest
    steps:
      - uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./elparadisogonzalo-monorepo
